import json
import random
import time
from datetime import timedelta
from typing import List, Dict, Any, Tuple, Optional
from services.optimization import FuelOptimizer
from services.graphhopper import GraphHopper
from utils.visualization import visualize_route 
import os
from pathlib import Path

class RouteComparator:
    def __init__(self, verbose: int = 1):
        self.verbose = verbose
        self.graphhopper = GraphHopper()
        self.optimizer = FuelOptimizer()
        self.output_dir = os.path.abspath("Fuel optimization")
        os.makedirs(self.output_dir, exist_ok=True)
        self.log_file_path = os.path.join(self.output_dir, "route_comparison_log.txt")
        self.num_routes = 100 
        self.sri_lanka_bounds = {
            "min_lat": 6.091419, "max_lat": 8.445618,
            "min_lon": 80.218134, "max_lon": 81.324091
        }

        # Pre-calculated fuel efficiency coefficients
        # Generated by update_custom_model() during run_comparisons()
        # Values represent relative fuel consumption (1.0 = baseline)

        self.fuel_coefficient_rules = {
            "road_class": {
                "MOTORWAY": 1.71,      # High-speed, optimized flow  
                "TRUNK": 1.02,         # Major highways, efficient  
                "PRIMARY": 1.0,        # Baseline (balanced efficiency)  
                "SECONDARY": 1.0,      # Similar to primary  
                "TERTIARY": 1.18,      # Lower priority, slight penalty  
                "UNCLASSIFIED": 1.35,  # Unknown conditions, higher penalty  
                "RESIDENTIAL": 0.85,   # Stop-and-go, but shorter distances  
                "LIVING_STREET": 1.04, # Low speed, mixed usage  
                "SERVICE": 0.86,       # Industrial/backroads, moderate penalty  
                "TRACK": 1.11,         # Rough but passable  
                "FOOTWAY": 1.06,       # Not ideal for vehicles  

                # Avoid these paths (no fuel data, assumed inefficient)  
                "PATH": 0.5,           # Footpaths (not for vehicles)  
                "PEDESTRIAN": 0.5,     # Walk-only zones  
                "CYCLEWAY": 0.55,      # Bike lanes  
                "STEPS": 0.4,          # Stairs (impassable)  
                "BRIDLEWAY": 0.4       # Horse paths  
            },
            "surface": {
                "GROUND": 0.99,       # Derived from data
                "PAVED": 0.75,        # Derived from data  
                "ASPHALT": 1.0,       # Baseline (ideal surface)  
                "CONCRETE": 1.0,      # Estimated (similar to asphalt)  
                "GRAVEL": 0.6,        # Estimated (rougher surface)  
                "DIRT": 0.6,          # Estimated (high resistance)  
                "SAND": 0.6,          # Estimated (very high resistance)  
                "COBBLESTONE": 0.75,  # Estimated (moderate resistance)  
                "PAVING_STONES": 0.75 # Estimated (similar to cobblestone)  
            },
            "other": {
                # All are Derived from data
                "toll": 1.1,
                "tunnel": 0.9,
                "bridge": 0.95,
                "lanes_ge_4": 1.1,
                "lanes_le_1": 0.9
            }
        }

    def _log(self, *args, level: int = 1):
        message = " ".join(str(arg) for arg in args)
        if self.verbose >= level:
            print(message)
        # Always write to log file regardless of verbosity level
        with open(self.log_file_path, "a", encoding="utf-8") as log_file:
            log_file.write(message + "\n")

    def _format_difference(self, value: float, unit: str = "km") -> str:
        """Format difference with appropriate sign"""
        if value >= 0:
            return f"+{abs(value):.2f} {unit}"
        return f"-{abs(value):.2f} {unit}"

    def _format_time_difference(self, ms_diff: float) -> str:
        """Format time difference in hh:mm:ss, handling negatives properly"""
        seconds_diff = ms_diff / 1000
        sign = "-" if seconds_diff < 0 else "+"
        abs_diff = abs(seconds_diff)
        
        hours = int(abs_diff // 3600)
        minutes = int((abs_diff % 3600) // 60)
        seconds = int(abs_diff % 60)
        
        return f"{sign}{hours:02d}:{minutes:02d}:{seconds:02d}"

    def _calculate_fuel_coefficient(self, road_details: Dict[str, Any]) -> float:
        """Calculate fuel coefficient based on road attributes"""
        coefficient = 1.0  # Default coefficient
        
        # Get road class coefficient
        road_class = road_details.get("road_class", "").upper()
        if road_class in self.fuel_coefficient_rules["road_class"]:
            coefficient *= self.fuel_coefficient_rules["road_class"][road_class]
        
        # Get surface coefficient
        surface = road_details.get("surface", "").upper()
        if surface in self.fuel_coefficient_rules["surface"]:
            coefficient *= self.fuel_coefficient_rules["surface"][surface]
        
        # Apply other coefficients
        if "toll" in road_details and road_details["toll"] != "MISSING":
            coefficient *= self.fuel_coefficient_rules["other"]["toll"]
        
        if road_details.get("road_environment") == "TUNNEL":
            coefficient *= self.fuel_coefficient_rules["other"]["tunnel"]
        elif road_details.get("road_environment") == "BRIDGE":
            coefficient *= self.fuel_coefficient_rules["other"]["bridge"]
        
        lanes = road_details.get("lanes", 0)
        if lanes >= 4:
            coefficient *= self.fuel_coefficient_rules["other"]["lanes_ge_4"]
        elif lanes <= 1:
            coefficient *= self.fuel_coefficient_rules["other"]["lanes_le_1"]
        
        return coefficient

    def _calculate_route_fuel_coefficient(self, route: Dict[str, Any]) -> float:
        """Calculate weighted average fuel coefficient for a route using RoadExtractor"""
        if not route or not route.get("paths"):
            self._log("No route or path data available", level=2)
            return 0.0
        
        path = route["paths"][0]
        instructions = path.get("instructions", [])
        total_distance = path["distance"]
        
        self._log(f"\nCalculating route fuel coefficient for {len(instructions)} segments", level=2)
        self._log(f"Total route distance: {total_distance/1000:.2f} km", level=2)
        
        if total_distance == 0:
            self._log("Route has zero distance", level=2)
            return 0.0
        
        # First, extract all OSM IDs with their point ranges
        osm_id_details = path.get("details", {}).get("osm_id", [])
        
        # Create a mapping of point index ranges to OSM IDs
        osm_id_map = {}
        for detail in osm_id_details:
            if len(detail) >= 3:  # Should be [start_index, end_index, osm_id]
                start_idx, end_idx, osm_id = detail[0], detail[1], detail[2]
                for idx in range(start_idx, end_idx + 1):
                    osm_id_map[idx] = osm_id
        
        weighted_sum = 0.0
        segment_count = 0
        
        for instruction in instructions:
            distance = instruction.get("distance", 0)
            interval = instruction.get("interval", [])
            segment_count += 1
            
            self._log(f"\nSegment {segment_count}: Distance = {distance}m", level=3)
            self._log(f"Instruction interval: {interval}", level=3)
            
            if len(interval) < 2:
                self._log("No valid interval for segment, using default coefficient 1.0", level=3)
                weighted_sum += 1.0 * distance
                continue
                
            start_idx, end_idx = interval[0], interval[1]
            segment_osm_ids = set()
            
            # Collect all unique OSM IDs for this segment
            for idx in range(start_idx, end_idx + 1):
                if idx in osm_id_map:
                    segment_osm_ids.add(osm_id_map[idx])
            
            if not segment_osm_ids:
                self._log(f"No OSM IDs found for segment points {start_idx}-{end_idx}, using default coefficient 1.0", level=3)
                weighted_sum += 1.0 * distance
                continue
            
            # Get road information from extractor
            road_coefficient = 1.0
            roads_found = 0
            
            for osm_id in segment_osm_ids:
                if osm_id in self.optimizer.extractor.roads:
                    road = self.optimizer.extractor.roads[osm_id]
                    roads_found += 1
                    
                    # Get all road attributes
                    road_attrs = {
                        "road_class": road.road_type.value,
                        "surface": road.osm_tags.get("surface", "").upper(),
                        "toll": "MISSING" if "toll" not in road.osm_tags else road.osm_tags["toll"],
                        "road_environment": "BRIDGE" if "bridge" in road.osm_tags else 
                                          "TUNNEL" if "tunnel" in road.osm_tags else "",
                        "lanes": int(road.osm_tags.get("lanes", 0)) if "lanes" in road.osm_tags else 0
                    }
                    
                    self._log(f"Road OSM ID {osm_id} attributes: {road_attrs}", level=3)
                    
                    # Calculate coefficient for this road
                    segment_coeff = self._calculate_fuel_coefficient(road_attrs)
                    road_coefficient = min(road_coefficient, segment_coeff)  # Use most restrictive coefficient
                    
            if roads_found == 0:
                self._log(f"No roads found in extractor for OSM IDs {segment_osm_ids}, using default coefficient 1.0", level=3)
                road_coefficient = 1.0
            
            weighted_sum += road_coefficient * distance
            self._log(f"Segment coefficient: {road_coefficient:.4f} * {distance}m = {road_coefficient * distance:.2f}", level=3)
            self._log(f"Running weighted sum: {weighted_sum:.2f}", level=3)
        
        route_coefficient = weighted_sum / total_distance
        self._log("\nFinal route coefficient calculation:", level=2)
        self._log(f"Total weighted sum: {weighted_sum:.2f}", level=2)
        self._log(f"Total distance: {total_distance}m", level=2)
        self._log(f"Route fuel coefficient: {route_coefficient:.4f}", level=2)
        
        return route_coefficient

    def _compare_routes(self, default_route: Dict[str, Any], custom_route: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """Compare routes and extract custom-only points"""
        if not default_route or not custom_route or not default_route.get("paths") or not custom_route.get("paths"):
            return None

        path1 = default_route["paths"][0]
        path2 = custom_route["paths"][0]

        distance_diff = path2["distance"] - path1["distance"]
        time_diff = path2["time"] - path1["time"]

        # Get coordinate points
        default_coords = set(tuple(coord) for coord in path1["points"]["coordinates"])
        custom_coords = [tuple(coord) for coord in path2["points"]["coordinates"]]

        # Get only custom-only points
        custom_only_points = [coord for coord in custom_coords if coord not in default_coords]

        return {
            "distance_diff": distance_diff,
            "distance_diff_formatted": self._format_difference(distance_diff / 1000, "km"),
            "time_diff": time_diff,
            "time_diff_formatted": self._format_time_difference(time_diff),
            "custom_only_points": custom_only_points  # Point-level difference only
        }

    def _generate_random_coordinates(self) -> List[Tuple[Tuple[float, float], Tuple[float, float]]]:
        """Generate valid coordinate pairs"""
        coord_generator = CoordinateGenerator(self.sri_lanka_bounds)
        return coord_generator.get_valid_coordinate_pairs(self.num_routes)

    def run_comparisons(self) -> Dict[str, List[Dict[str, Any]]]:
        """Run the route comparison process"""
        self._log("Starting route comparisons...")
        
        # Load custom model
        custom_model_path = Path("custom_model.json")
        if not custom_model_path.exists():
            self._log("Custom model not found, creating a new one...")
            self.optimizer.update_custom_model()
        
        with open(custom_model_path) as f:
            custom_model = json.load(f)
        
        results = {
            "with_differences": [],
            "no_differences": []
        }

        coordinate_pairs = self._generate_random_coordinates()
        output_path = os.path.join(self.output_dir, "route_comparisons.json")

        for i, (start, end) in enumerate(coordinate_pairs, 1):
            self._log(f"\nProcessing route {i}/{len(coordinate_pairs)}: {start} -> {end}")
            
            # Get route without custom model
            self._log("Requesting default route...", level=2)
            default_route = self.graphhopper.request_route(start, end)
            
            self._log("Requesting custom route...", level=2)
            # Get route with custom model
            custom_route = self.graphhopper.request_route(start, end, custom_model)
            
            if not default_route or not custom_route:
                self._log(f"Skipping failed route between {start} and {end}", level=1)
                continue
                
            comparison = self._compare_routes(default_route, custom_route)

            # Calculate fuel coefficients using optimizer's extractor
            default_fuel_coeff = self._calculate_route_fuel_coefficient(default_route)
            custom_fuel_coeff = self._calculate_route_fuel_coefficient(custom_route)
            
            # Calculate fuel improvement percentage
            fuel_improvement = 0.0
            if custom_fuel_coeff != 0:
                fuel_improvement = (1 - default_fuel_coeff/custom_fuel_coeff) * 100

            result = {
                "start": start,
                "end": end,
                "default": {
                    "distance": default_route["paths"][0]["distance"],
                    "time": default_route["paths"][0]["time"],
                    "fuel_coefficient": default_fuel_coeff
                },
                "custom": {
                    "distance": custom_route["paths"][0]["distance"],
                    "time": custom_route["paths"][0]["time"],
                    "fuel_coefficient": custom_fuel_coeff
                },
                "fuel_improvement": fuel_improvement
            }
            
            if comparison and (comparison["distance_diff"] != 0 or comparison["time_diff"] != 0):
                result["differences"] = comparison
                results["with_differences"].append(result)

                # ✅ VISUALIZE AND SAVE ROUTE
                filename = f"route_for_{start[0]:.4f}_{start[1]:.4f}_to_{end[0]:.4f}_{end[1]:.4f}.html"
                self._log(f"Generating visualization: {filename}", level=2)
                visualize_route(start, custom_route, custom_model, output_file=filename, differences=comparison)
            else:
                results["no_differences"].append(result)
            
            # Save progress periodically
            if i % 100 == 0 or i == len(coordinate_pairs):
                self._log(f"Processed {i} routes... saving progress", level=1)
                with open(output_path, "w") as f:
                    json.dump(results, f, indent=2)
            
            time.sleep(0.1)  # Rate limiting
        
        self._print_summary(results)
        return results

    def _print_summary(self, results: Dict[str, List[Dict[str, Any]]]) -> None:
        """Print summary of comparison results"""
        self._log("\n=== Results Summary ===")
        self._log(f"Total routes processed: {len(results['with_differences']) + len(results['no_differences'])}")
        self._log(f"Routes with differences: {len(results['with_differences'])}")
        self._log(f"Routes without differences: {len(results['no_differences'])}")
        
        # Print all examples with differences
        if results["with_differences"]:
            self._log("\n=== Routes With Differences ===")
            count = 0
            for i, example in enumerate(results["with_differences"], 1):
                # Skip routes with fuel improvement less than 4%
                if example['fuel_improvement'] < 4.0:
                    continue
                count += 1
                self._log(f"\n--- Route {i} ---")
                self._log(f"From {example['start']} to {example['end']}")
                self._log(f"Default: {example['default']['distance']/1000:.2f} km, "
                    f"{timedelta(seconds=example['default']['time']/1000)}, "
                    f"fuel coefficient: {example['default']['fuel_coefficient']:.2f}")
                self._log(f"Custom: {example['custom']['distance']/1000:.2f} km, "
                    f"{timedelta(seconds=example['custom']['time']/1000)}, "
                    f"fuel coefficient: {example['custom']['fuel_coefficient']:.2f}")
                self._log(f"Distance difference: {example['differences']['distance_diff_formatted']}")
                self._log(f"Time difference: {example['differences']['time_diff_formatted']}")
                self._log(f"Fuel ratio improvement: {example['fuel_improvement']:.1f}%")

            self._log(f"Total route with >= 4% influence is {count}")

        # Print all examples without differences
        # if results["no_differences"]:
        #     self._log("\n=== Routes Without Differences ===")
        #     for i, example in enumerate(results["no_differences"], 1):
        #         self._log(f"\n--- Route {i} ---")
        #         self._log(f"From {example['start']} to {example['end']}")
        #         self._log(f"Distance: {example['default']['distance']/1000:.2f} km (same in both)")
        #         self._log(f"Time: {timedelta(seconds=example['default']['time']/1000)} (same in both)")
        #         self._log(f"Fuel coefficient: {example['default']['fuel_coefficient']:.2f} (same in both)")

class CoordinateGenerator:
    def __init__(self, bounds: Dict[str, float]):
        self.bounds = bounds
        self._validate_bounds()
        
    def _validate_bounds(self) -> None:
        """Ensure bounds are valid (min < max)"""
        if (self.bounds["min_lat"] >= self.bounds["max_lat"] or 
            self.bounds["min_lon"] >= self.bounds["max_lon"]):
            raise ValueError("Invalid bounds: min values must be less than max values")
        
    def generate_random_point(self) -> Tuple[float, float]:
        """Generate a random point within Sri Lanka with validation"""
        lat = random.uniform(self.bounds["min_lat"], self.bounds["max_lat"])
        lon = random.uniform(self.bounds["min_lon"], self.bounds["max_lon"])
        return (lat, lon)
    
    def get_valid_coordinate_pairs(self, num_pairs: int) -> List[Tuple[Tuple[float, float], Tuple[float, float]]]:
        """Generate N valid coordinate pairs with error handling"""
        pairs = []
        attempts = 0
        max_attempts = num_pairs * 3  # More generous attempt limit
        
        while len(pairs) < num_pairs and attempts < max_attempts:
            try:
                start = self.generate_random_point()
                end = self.generate_random_point()
                # Simple validation that points aren't identical
                if start != end:
                    pairs.append((start, end))
            except Exception as e:
                print(f"Coordinate generation error: {e}")
                attempts += 1
                
        if len(pairs) < num_pairs:
            print(f"Warning: Only generated {len(pairs)}/{num_pairs} valid coordinate pairs")
            
        return pairs

if __name__ == "__main__":
    comparator = RouteComparator(verbose=2)
    comparator.run_comparisons()